# Generated by Django 5.2.6 on 2025-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('jogador', models.CharField(blank=True, max_length=120)),
                ('personagem', models.CharField(max_length=120)),
                ('raca', models.CharField(blank=True, max_length=80)),
                ('origem', models.CharField(blank=True, max_length=80)),
                ('classe', models.CharField(blank=True, max_length=80)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('divindade', models.CharField(blank=True, max_length=120)),
                ('tendencia', models.CharField(blank=True, max_length=40)),
                ('forca', models.IntegerField(default=10)),
                ('destreza', models.IntegerField(default=10)),
                ('constituicao', models.IntegerField(default=10)),
                ('inteligencia', models.IntegerField(default=10)),
                ('sabedoria', models.IntegerField(default=10)),
                ('carisma', models.IntegerField(default=10)),
                ('pv_max', models.IntegerField(default=0)),
                ('pv_atual', models.IntegerField(default=0)),
                ('pm_max', models.IntegerField(default=0)),
                ('pm_atual', models.IntegerField(default=0)),
                ('defesa_base', models.IntegerField(default=10)),
                ('armadura', models.IntegerField(default=0)),
                ('escudo', models.IntegerField(default=0)),
                ('penalidade_armadura', models.IntegerField(default=0)),
                ('outros_modificadores_defesa', models.IntegerField(default=0)),
                ('pericias', models.JSONField(blank=True, default=dict)),
                ('poderes', models.JSONField(blank=True, default=list)),
                ('magias', models.JSONField(blank=True, default=list)),
                ('inventario', models.JSONField(blank=True, default=list)),
                ('anotações', models.TextField(blank=True)),
                ('tesouro', models.CharField(blank=True, max_length=100)),
                ('carga', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
